
title: Web Design
author: uniqueWTS
email: 710029721@qq.com
description: >- 
  My own blog on GitHub, only for Web design purples.
baseurl: "/blog" # the subpath of your site, e.g. /blog．change it to your repo's name on github.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  uniqueWTS

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Customize navigation links
#header_pages:
#  - about.md
#  - portfolio.md

# 显示摘要
# show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
